create table public.error_events
(
    event_id                   integer generated by default as identity
        constraint error_events_pk
            primary key,
    lob_app_id                 integer                                       not null
        constraint error_events_lob_applications_id_fk
            references public.lob_applications,
    event_state                varchar(100) default 'NEW'::character varying not null,
    correlation_id             varchar(100),
    span_id                    varchar(100),
    stacktrace                 text,
    origin_method              text,
    resolution                 text,
    pull_request_url           text,
    confidence                 varchar(10),
    user_resolution_acceptance varchar(10),
    occurrence_count           integer      default 1                        not null,
    created_ts                 timestamp    default now()                    not null,
    updated_ts                 timestamp    default now()                    not null,
    stacktrace_vec             vector(128),
    error_timestamp            timestamp                                     not null,
    user_feedback              text,
    origin_line_number         integer      default 0                        not null,
    origin_class               varchar(255),
    source_branch              varchar(255),
    affected_jira_ids          text
);

comment on column public.error_events.user_resolution_acceptance is 'LIKE or DISLIKE';

alter table public.error_events
    owner to patch_user;

